######## transform.py ########
transform_train:
  input: data/raw/train/train.csv
  output: data/transformed/train
  output_filename: train.parquet

transform_test:
  input: data/raw/test/test.csv
  output_filename: test.parquet
  output: data/transformed/test

transform_wind:
  input: data/raw/windforecasts
  output: data/transformed/windforecasts

######## clean.py ########
clean_train:
  input: data/transformed/train/train.parquet
  output: data/cleaned/train
  output_filename: train.parquet

clean_test:
  input: data/transformed/test/test.parquet
  output_filename: test.parquet
  output: data/cleaned/test

clean_wind:
  input: data/transformed/windforecasts
  output: data/cleaned/windforecasts